### ISSUE TITLE
wsgi

### ISSUE THREAD

**Issue by uhuntu** [pawnhearts/django_react_admin#1]
Please think about how to use in wsgi env.

**Comment by pawnhearts** [comment]
What do you mean? You just have to pass /static/ to http server as usual.

**Comment by uhuntu** [comment]
in /usr/local/lib/python3.8/dist-packages/django_react_admin/urls.py

I must setup

```
def show_index_html(request):
    with open('/var/www/static/django_react_admin/index.html', 'r') as f:
        return HttpResponse(f.read())
```

IMO, "open" just can open local file system but not server related address.

When you run ```manage.py runserver```, as it runs from local, so it can match static/django_react_admin/index.html

But when it run from wsgi for apache2, it can not know how to look for static/django_react_admin/index.html, I must indicate full address.

**Comment by pawnhearts** [comment]
I see. I've fixed your issue in a bit different way.
